steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/private/web-admin:$COMMIT_SHA', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/$PROJECT_ID/private/web-admin:$COMMIT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'web-admin'
    - '--image'
    - 'us-east1-docker.pkg.dev/$PROJECT_ID/private/web-admin:$COMMIT_SHA'
    - '--region'
    - 'us-east1'
    - '--concurrency'
    - '20'
    - '--max-instances'
    - '2'
    - '--memory'
    - '128Mi'
    - '--platform'
    - 'managed'
    - '--service-account'
    - 'dummy-service@oceanblue.iam.gserviceaccount.com'
    - '--allow-unauthenticated'
images:
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/private/web-admin:$COMMIT_SHA'
