name: Build and Deploy

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Lint Server
      uses: georgemblack/actions/yarn-command@1.0.4
      with:
        command: lint
        directory: ./server
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
    - name: Cloud Run Deploy
      uses: georgemblack/actions/cloud-run-deploy@1.0.4
      with:
        serviceName: web-admin
        projectId: ${{ secrets.GCLOUD_PROJECT_ID }}
        runtimeServiceAccount: ${{ secrets.GCLOUD_RUNTIME_SERVICE_ACCOUNT }}
        cloudBuildBucket: artifacts.oceanblue.appspot.com
        region: us-east1
        concurrency: 20
        maxInstances: 1
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
